# Generated by Django 4.1.1 on 2022-09-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cook', '0003_recipe_choices_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
