# Generated by Django 4.1.1 on 2022-09-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cook", "0004_ingredient_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="choices",
        ),
        migrations.AlterField(
            model_name="recipe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cook.ingredient",
            ),
        ),
    ]
